### ISSUE TITLE
Load events from a file instead of from an enum

### ISSUE THREAD

**Issue by IronicallySerious** [TheChernoCommunity/GameProject-1#9]
https://github.com/TheChernoCommunity/GameProject-1/blob/4bb487b7b64c3be20e783a2dc0d94b0b7413a72a/src/Engine/Events/Event.h#L13

Might be better to load these in at runtime from like an ini file/json file. This will probably send the entire engine to recompile (because events will probably be used everywhere) even with one line changes like adding a new event.

**Comment by sfulham** [comment]
The event types are hardly ever gonna change so this is kinda unneccesary.

**Comment by IronicallySerious** [comment]
@sfulham Game specific events would change a lot I assume. Also going forward I think it is safe to assume the event list will expand

**Comment by sfulham** [comment]
Also, loading from a file isn't gonna change anything as those are only to get the type of event that has been dispatched which has to be from an enum anyway as it has to be known at compilation.
